### ISSUE TITLE
Adding performance enhancing mods.

### ISSUE THREAD

**Issue by kazuviking2** [MLDEG/Ragnamod_VII#115]
### Describe the feature

Adding performance mods because the modpack is lacking them. Mods i added:
Redirector, Starlight, TexTrue's Embeddium Options, Dimensional Threading Reforked, Fast Async World Save, Fastload Reforged, fix GPU memory leak, Entity Collision FPS Fix, Let Me Despawn, 

### Reasons why this should be added

I went from unplayable stutthery mess to a stable 75fps with no lag spikes.

**Comment by MLDEG** [comment]
The modpack has no lacking of performance mods, it's your PC that lacks performance, not being mean.
I played the pack from start to finish with 60FPS, and you really don't need more.

Now regarding the mods you suggest I have some problems.
I don't know them all and doing in-depth tests would take time, whereas for me the modpack doesn't need it.
Then Starlight is not compatible with the pack (I had to remove it at one point)
TexTrue's Embeddium Options breaks certain textures (notably the twilight chest and blue skies) don't know what else it breaks, so I didn't add it.

I'll still look at the other mods that you proposed, for curiousity, but know one VERY important thing!!
Since you added mods to the modpack, this does not become my modpack anymore and therefore if you have any problem, whatever it may be, it will no longer be my problem either :)
If you are ok with that then there is no problem
