### ISSUE TITLE
[Bug]: Draconic reactor core invisible

### ISSUE THREAD

**Issue by RaiiZou** [MLDEG/Ragnamod_VII#20]
### Modpack version

7.0.12

### Description

I wanted to do the reactor core but he's invisible, first I try to reconnect to the server to make sure it was not a simple display bug but nothing changed then a friend came to see but he also did not see it, I search on the internet but all I found in relation to this bug is a compatibility problem with a mod named ribidium but after verification, I did not find this mod in the list

![2024-01-22_23 26 13](https://github.com/MLDEG/Ragnamod_VII/assets/83038640/0042266d-6545-4444-b9f4-03fbefe2c707)
![2024-01-22_23 25 04](https://github.com/MLDEG/Ragnamod_VII/assets/83038640/1a389fb2-caa5-4374-93c9-8c9f6123c94b)

### Steps to reproduce

Place reactor core

### Expected behavior

Nothing

**Comment by MLDEG** [comment]
Hi,
Indeed, by removing the Embbedium mod from the modpack (which is a fork of Rubidium) the Draconic Core is visible.
![2024-01-23_00 20 40](https://github.com/MLDEG/Ragnamod_VII/assets/90324978/d1437b86-a264-4b3d-9a5e-92404d924547)
So, you can remove the mod from your instance (which is not required for Server, because it improves client performance).
I will not remove the mod from the modpack, however I will add an annotation on the questbook to keep everyone informed of the visual problem!

Finally, I would like to draw your attention to this line when you send an issue:
_If you are not using the latest version, make sure to update it before submitting your issue._
I didn't automatically close your message because I hadn't noticed that you were still in 7.0.12, but technically I should have ^^'

So be aware of that and thank to you report :)

**Comment by RaiiZou** [comment]
Yes sorry, I just noticed the update and since I am on a private server, I was not able to do the update immediately but I still took the time to check if the bug had been fixed.

Getting back to the solutions, actually removing Embbedium solves the problem but it causes me a huge loss of FPS, I will find a way to have both and in the worst case, I removed it while preparing the reactor then I would put it back
